Repository crest-cassia/oacis, pull requests merged in 2019-12, with the labels that each got.

#662 prevent overwriting locale in JobScript
  lib/job_script_util.rb
Labels: enhancement

#663 show results in a deeper directory
  app/helpers/runs_helper.rb
Labels: enhancement

#664 add toggle status button at host/show page
  app/controllers/hosts_controller.rb
  app/views/hosts/_about.html.haml
Labels: enhancement

#665 improve the format of Run CSV
  app/models/simulator.rb
  app/views/simulators/_parameter_sets_list.html.haml
  spec/models/simulator_spec.rb
Labels: enhancement

#667 bugfix: the last column is not shown in show/hide column button
  app/assets/javascripts/parameter_set.js
Labels: bug

#666 added tooltips on data_tables
  app/datatables/parameter_sets_list_datatable.rb
  app/datatables/runs_list_datatable.rb
Labels: enhancement

#668 updated gems
  Gemfile.lock
Labels: refactoring

#670 Revert develop
  app/controllers/runs_controller.rb
  app/models/simulator.rb
  app/models/webhook.rb
  app/workers/webhook_sender.rb
  app/workers/webhook_sender_worker.rb
  lib/tasks/boot_webhook_sender_worker.rb
  lib/tasks/daemon.rake
  spec/models/webhook_spec.rb
Labels: bug

#673 set Simulator#executable_on by default
  app/controllers/simulators_controller.rb
  spec/controllers/simulators_controller_spec.rb
Labels: enhancement
